### ISSUE TITLE
[1.18.1] Crash after generating a World

### ISSUE THREAD

**Issue by pewblaze** [Lex305/Spelunker#1]
I'm not sure if its this mod, but i updated it & it crashed today. 
[crash-2022-01-28_00.42.10-client.txt](https://github.com/Lex305/Spelunker/files/7954579/crash-2022-01-28_00.42.10-client.txt)

I installed the older version and it works.

**Comment by Leximon** [comment]
thx for your report, I'll look forward to fixing this as soon as possible

**Comment by Leximon** [comment]
should be fixed now

**Comment by pewblaze** [comment]
Thank you!
