### ISSUE TITLE
Amethyst Dust doesn't drop

### ISSUE THREAD

**Issue by doctor4t** [Lex305/Spelunker#11]
What it says on the tin. I have broken around 20 stacks of Amethyst Clusters in survival to no avail.

I wondered if it was the config, so I tried resetting it multiple times, no "allowBrewing" options appear in the config file. From looking at the code it seems to be enabled by default, so I'm not sure what I'm doing wrong.

Using version 1.3.0

**Comment by Leximon** [comment]
It works completely fine for me, using version 1.3.0.

Did you accidentally use silk touch? This is the only reason I could think of.
The version on this GitHub repository is still unreleased and before I am going to publish this I'd like to ask you to try this version to see if this would fix your issue.
[spelunker-1.4.0.zip](https://github.com/Leximon/Spelunker/files/8720816/spelunker-1.4.0.zip)

**Comment by doctor4t** [comment]
No I didn't use Silk Touch. I'll try with 1.4.0

**Comment by doctor4t** [comment]
After testing on 1.4.0, it works in an environment with only Spelunker, but still not in my pack. Must be a mod interferring with the drop code, I'll do more tests and find a culprit.

**Comment by doctor4t** [comment]
After more testing, it seems 1.4.0 did fix it for my pack, so my mistake! I guess I just got very unlucky when I tested it originally.
