### ISSUE TITLE
[1.18.2 Fabric] Ticking World causes server to crash

### ISSUE THREAD

**Issue by TofuToons** [Lex305/Spelunker#12]
Version: Spelunker-1.4.0 (1.18.2 Fabric)

Seems to crash server when using the potion for too long. Here is the crash log.
[crash-2022-07-12_20.30.53-server.txt](https://github.com/Leximon/Spelunker/files/9096894/crash-2022-07-12_20.30.53-server.txt)

Basically I was experimenting with the potion and after a good 5+ minutes of having the potion effect active, it crashed the server.
Here is also the config, incase that is useful as I added other modded ores to it.
[spelunker.txt](https://github.com/Leximon/Spelunker/files/9096912/spelunker.txt)
(Changed it to txt to attach to this post)

Thank you!

**Comment by Leximon** [comment]
Hopfully this will fix it 1b878a3e1cc026e617244240ad9e26fa328450cf
Thanks for your report! I will upload the update asap
