### ISSUE TITLE
[Bug] Crash when installed on dedicated server

### ISSUE THREAD

**Issue by lizfinite** [Lex305/Spelunker#2]
Steps to reproduce:
- Create a dedicated server with fabric-server-loader, and install Spelunker and fabric api
- Attempt to launch the server
- Crash

**Expected Result:**
- Don't crash

**Addition information;**
Server Log of the crash: [https://paste.ee/p/Ui5tt](https://paste.ee/p/Ui5tt)

**Comment by Leximon** [comment]
thx should be fixed now
