### ISSUE TITLE
Spelunker Causes Lag

### ISSUE THREAD

**Issue by CammiePone** [Lex305/Spelunker#3]
So, we've been having some issues with lag in a private pack, so we profiled it and Spelunker ended up being the cause of most of it. We also tested with Spelunker on its own, which is the profile below. Removing it fixed the lag issues we'd been having, but I thought it would be a good idea to report it to you anyways.

Here's the spark profile:
https://spark.lucko.me/OhUopjRLnH

Setting it to sources view lets you quickly and easily see where the problem is.

![image](https://user-images.githubusercontent.com/16853086/161881287-21aa8cd2-0861-4183-880d-d26f5e7f9d09.png)

**Comment by Leximon** [comment]
thx for your report!
Is this only an issue if the player has the spelunker effect or is this a general problem?

**Comment by CammiePone** [comment]
A general problem. In both tests, we've never once had the spelunker effect applied

**Comment by Leximon** [comment]
I think this issue should be fixed now. I will release this update soon and thx again for your report! :D

**Comment by CammiePone** [comment]
thank you \o/
