### ISSUE TITLE
[1.18.2] Really big lag on server after drinking Spelunker Potion

### ISSUE THREAD

**Issue by pewblaze** [Lex305/Spelunker#8]
Hi so i am testing our server atm & i found a spelunker potion.
After drinking it i got a really big lag, i was kicked from the server & after reconnecting lag was gone ^^

My latest client log: (not sure if you need that)
[latest.log](https://github.com/Leximon/Spelunker/files/8544384/latest.log)

I used spark atm so i got this:
![grafik](https://user-images.githubusercontent.com/96242065/164803121-176276c7-3fa4-455e-ad15-0414175b25a8.png)

**Comment by Rasmion** [comment]
There is already a newer version in progress, which will probably fix this bug
